'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class AddProduct
    
    '''<summary>
    '''LabelProductId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelProductId As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TextBoxProductId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxProductId As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''LabelCategory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelCategory As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''DropDownListCategoryId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DropDownListCategoryId As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''rfvproductcategory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvproductcategory As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''LabelProductName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelProductName As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TextBoxProductName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxProductName As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''rfvproductname control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvproductname As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''LabelProductDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelProductDescription As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TextBoxProductDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxProductDescription As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''rfvproductdescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvproductdescription As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''LabelProductPrice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelProductPrice As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TextBoxProductPrice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxProductPrice As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''rfvproductprice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvproductprice As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''LabelProductQuantity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelProductQuantity As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TextBoxProductQuantity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxProductQuantity As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''rfvproductquantity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvproductquantity As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''LabelProductImage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelProductImage As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''FileUploadProductImage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FileUploadProductImage As Global.System.Web.UI.WebControls.FileUpload
    
    '''<summary>
    '''ImageProduct control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ImageProduct As Global.System.Web.UI.WebControls.Image
    
    '''<summary>
    '''rfvproductimage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvproductimage As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''ButtonClear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonClear As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''ButtonAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonAdd As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''LabelStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelStatus As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''LabelStatusImage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelStatusImage As Global.System.Web.UI.WebControls.Label
End Class
