'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Checkout
    
    '''<summary>
    '''LabelTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelTitle As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''GridViewCheckout control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridViewCheckout As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''LabelOrderDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelOrderDetails As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TextBoxOrderId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxOrderId As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TextBoxDateOfOrder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxDateOfOrder As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TextBoxUsername control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxUsername As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TextBoxEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxEmail As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TextBoxPhoneNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxPhoneNumber As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TextBoxAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxAddress As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''LabelEwalletAccountId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelEwalletAccountId As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''LabelEWalletBalance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelEWalletBalance As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''LabelTitleSelectPayment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelTitleSelectPayment As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''RadioButtonListPayment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadioButtonListPayment As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''ButtonCash control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonCash As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''ButtonEwallet control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonEwallet As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''ButtonCancelShopping control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonCancelShopping As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''LabelCustomerId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelCustomerId As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''LabelTransactionId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelTransactionId As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''LabelEwalletBalanceStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelEwalletBalanceStatus As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''LabelStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelStatus As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''LabelProductIdInGridview control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelProductIdInGridview As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''LabelProductQuantityInGridview control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelProductQuantityInGridview As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''LabelGetEmailValueFromSession control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelGetEmailValueFromSession As Global.System.Web.UI.WebControls.Label
End Class
