'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Deposit
    
    '''<summary>
    '''LabelTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelTitle As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''LabelAccountId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelAccountId As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TextBoxAccountId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxAccountId As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''LabelDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelDate As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TextBoxDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxDate As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''LabelBalance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelBalance As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TextBoxBalance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxBalance As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''LabelDeposit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelDeposit As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TextBoxDeposit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxDeposit As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''rfvdeposit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvdeposit As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''ButtonClear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonClear As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''ButtonDeposit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonDeposit As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''HyperLinkDeposit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HyperLinkDeposit As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''HyperLinkWithdraw control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HyperLinkWithdraw As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''HyperLinkTransfer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HyperLinkTransfer As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''HyperLinkTransactionHistory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HyperLinkTransactionHistory As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''LabelStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelStatus As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''LabelTransactionId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelTransactionId As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''LabelGetEmailValueFromSession control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelGetEmailValueFromSession As Global.System.Web.UI.WebControls.Label
End Class
