'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class OrderHistoryDetails
    
    '''<summary>
    '''GridViewOrderDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridViewOrderDetails As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''SqlDataSourceOrderDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSourceOrderDetails As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''PanelReceipt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanelReceipt As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''LabelOrderId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelOrderId As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''LabelOrderDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelOrderDate As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''LabelCustomerName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelCustomerName As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''LabelCustomerEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelCustomerEmail As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''LabelCustomerPhoneNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelCustomerPhoneNumber As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''LabelCustomerAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelCustomerAddress As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''LabelPaymentType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelPaymentType As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''GridViewProductReceipt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridViewProductReceipt As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''LabelTotal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelTotal As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ButtonDownload control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonDownload As Global.System.Web.UI.WebControls.Button
End Class
