'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ShoppingCart

    '''<summary>
    '''LabelShoppingCartQuantity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelShoppingCartQuantity As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''HyperLinkContinueShopping control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HyperLinkContinueShopping As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''GridViewShoppingCart control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridViewShoppingCart As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''ButtonCheckout control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonCheckout As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''LinkButtonClearShoppingCart control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LinkButtonClearShoppingCart As Global.System.Web.UI.WebControls.LinkButton
End Class
