'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Transfer
    
    '''<summary>
    '''LabelFromAccountId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelFromAccountId As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TextBoxFromAccountId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxFromAccountId As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''LabelToAccountId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelToAccountId As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TextBoxToAccountId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxToAccountId As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''rfvrecipient control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvrecipient As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''LabelDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelDate As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TextBoxDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxDate As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''LabelBalance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelBalance As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TextBoxBalance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxBalance As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''LabelTransferAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelTransferAmount As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TextBoxTransferAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxTransferAmount As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''rfvtransferamount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvtransferamount As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''ButtonClear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonClear As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''ButtonTransfer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonTransfer As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''HyperLinkDeposit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HyperLinkDeposit As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''HyperLinkWithdraw control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HyperLinkWithdraw As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''HyperLinkTransfer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HyperLinkTransfer As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''HyperLinkTransactionHistory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HyperLinkTransactionHistory As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''LabelStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelStatus As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''LabelTransactionId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelTransactionId As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''LabelGetEmailValueFromSession control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelGetEmailValueFromSession As Global.System.Web.UI.WebControls.Label
End Class
